const Layout = () => import('@/layout/user-layout.vue')

export default {
  name: 'User',
  path: '/user',
  component: Layout,
  redirect: '/user/index',
  meta: {
    title: '示例页面',
    icon: 'uil:pagelines',
    role: [],
    requireAuth: false,
    order: 1,
  },
  children: [
    {
      name: 'UserIndex',
      path: 'index',
      component: () => import('./index.vue'),
      meta: {
        title: '首页',
        icon: 'ic:baseline-table-view',
        role: [],
        requireAuth: false,
        keepAlive: true,
      },
    },
    {
      name: 'ExamList',
      path: 'exam-list',
      component: () => import('./exam-list/index.vue'),
      meta: {
        title: '考试',
        icon: 'ic:baseline-table-view',
        role: ['student'],
        requireAuth: true,
        keepAlive: true,
      },
    },
    {
      name: 'ProblemList',
      path: 'problem-list',
      component: () => import('./problem-list/index.vue'),
      meta: {
        title: '考试题目列表',
        icon: 'ic:baseline-table-view',
        role: ['student'],
        requireAuth: true,
        keepAlive: false,
      },
    },
    {
      name: 'TrainList',
      path: 'train-list',
      component: () => import('./train-list/index.vue'),
      meta: {
        title: '训练题目列表',
        icon: 'ic:baseline-table-view',
        role: ['student'],
        requireAuth: true,
        keepAlive: false,
      },
    },
    {
      name: 'TakeClass',
      path: 'take-class',
      component: () => import('./take-class/index.vue'),
      meta: {
        title: '加入班级',
        icon: 'ic:baseline-table-view',
        role: ['student'],
        requireAuth: true,
        keepAlive: true,
      },
    },
    {
      name: 'FAQ',
      path: 'faq',
      component: () => import('./faq/index.vue'),
      meta: {
        title: '常见问题及解答',
        icon: 'ic:baseline-table-view',
        role: [],
        requireAuth: false,
        keepAlive: true,
      },
    },
    {
      name: 'Signup',
      path: 'signup',
      component: () => import('./signup/index.vue'),
      meta: {
        title: '注册',
        icon: 'ic:baseline-table-view',
        role: [],
        requireAuth: false,
        keepAlive: true,
      },
    },
    {
      name: 'RePwInfo',
      path: 're-pw-info',
      component: () => import('./re-pw-info/index.vue'),
      meta: {
        title: '学生重置密码',
        icon: 'ic:baseline-table-view',
        role: [],
        requireAuth: false,
        keepAlive: true,
      },
    },
    {
      name: 'ResetPassword',
      path: 'reset-password',
      component: () => import('./reset-password/index.vue'),
      meta: {
        title: '学生重置密码',
        icon: 'ic:baseline-table-view',
        role: [],
        requireAuth: false,
        keepAlive: true,
      },
    },
    {
      name: 'PersonSetting',
      path: 'person-setting',
      component: () => import('./person-setting/index.vue'),
      meta: {
        title: '个人设置',
        icon: 'ic:baseline-table-view',
        role: ['student'],
        requireAuth: true,
        keepAlive: false,
      },
    },
  ],
}
